// @vitest-environment jsdom

import "@testing-library/jest-dom/vitest";

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { ProjectCard } from "#/ui/project-card";
import { SiteHeader } from "#/ui/site-header";
import { SourceBadge } from "#/ui/source-badge";
import { StatusRail } from "#/ui/status-rail";

const card = {
  source: "camara" as const,
  externalId: "501",
  officialCode: "PEC 8/2025",
  officialTitle: "Proposta de Emenda à Constituição nº 8, de 2025",
  officialSummary: "Reduz a jornada semanal e altera a escala de trabalho.",
  officialUrl: "https://www.camara.leg.br/propostas-legislativas/501",
  statusLabel: "Aguardando parecer na comissão",
  originHouse: "camara" as const,
  currentHouse: "camara" as const,
  presentedAt: "2025-02-01T12:00:00.000Z",
  checkedAt: "2026-09-03T12:00:00.000Z",
  latestActivityAt: "2026-08-31T18:00:00.000Z",
  topics: ["Trabalho e Emprego"],
  authors: [
    {
      source: "camara" as const,
      name: "Ana Cidadã",
      party: "ABC",
      kind: "Deputada Federal",
      primary: true,
      lawmakerExternalId: "100",
      officialUrl: "https://www.camara.leg.br/deputados/100",
    },
  ],
};

describe("civic interface components", () => {
  it("provides a named primary navigation", () => {
    render(<SiteHeader />);

    expect(screen.getByRole("navigation", { name: "Navegação principal" })).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "Pulso Público" })).toHaveAttribute("href", "/");
    expect(screen.getByRole("link", { name: "Seguindo" })).toHaveAttribute("href", "/seguindo");
  });

  it("describes the official source with text", () => {
    render(<SourceBadge source="senado" />);

    expect(screen.getByText("Senado Federal")).toBeInTheDocument();
  });

  it("shows status as text and identifies it as official", () => {
    render(<StatusRail status="Aguardando parecer na comissão" source="camara" />);

    expect(screen.getByText("Situação oficial")).toBeInTheDocument();
    expect(screen.getByText("Aguardando parecer na comissão")).toBeInTheDocument();
  });

  it("renders official project facts without claiming they were generated by AI", () => {
    render(<ProjectCard project={card} />);

    expect(screen.getByRole("link", { name: /PEC 8\/2025/ })).toHaveAttribute(
      "href",
      "/projetos/camara/501",
    );
    expect(screen.getByText("Título oficial")).toBeInTheDocument();
    expect(screen.queryByText("Gerado por IA")).not.toBeInTheDocument();
    expect(screen.getByText(/Ana Cidadã/)).toBeInTheDocument();
  });

  it("shows that official activity is unavailable when no official date exists", () => {
    const view = render(<ProjectCard project={{ ...card, latestActivityAt: null }} />);

    expect(view.container).toHaveTextContent("Atividade oficial não disponível");
    expect(view.container.querySelector("time")).not.toBeInTheDocument();
  });
});
